version: "3.9"
services:
  
  # Jenkins service
  jenkins_cicd:
    image: jenkins/jenkins:lts
    ports:
      - 8080:8080   # Expose port 8080 (right) of the container to the port 8080 (left) of the host ( Jenkins web )
      - 50000:50000 # Agent Jenkins needed for the good works of the services
    volumes:
      - ./Jenkins/config:/var/jenkins_home # put all the config file into 'config' in the host for a 'backup'
    networks:
      - cicd
  
  # Prometheus service to get the metrics of jenkins ( data system )
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ../Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml # Mount the prometheus's config file into the contener, for personal configuration
      - ../Prometheus/data:/prometheus/data # a 'backup' for the data in local
    networks:
      - cicd 

  # Grafana image to use the metric that prometheus got into visual ( diagram, table and so on )
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    user: "1000" # the user id to let the permission in the container to access the file
    volumes:
      - ../Grafana/grafana_data:/var/lib/grafana # grafana backup
    networks:
      - cicd

# Test containers used for ping, request test (curl) and other debug things
  test:
    image: alpine
    command: tail -f /dev/null
    networks:
      - cicd

# Put all the containers into a network, for the communication between each others
networks:
    cicd:
      driver: bridge
      ipam:
        driver: default
        config:
          - subnet: 192.168.2.0/24
